var itemSold = {

    block: {
        side1: 'Little Bird Toy Co Site Photos/block2.jpg',
        side2: 'Little Bird Toy Co Site Photos/block1.jpg',
        side3: 'Little Bird Toy Co Site Photos/block3.jpg',
        display: 'Little Bird Toy Co Site Photos/block2.jpg',
        title: 'Handcrafted Wooden Toy Building Block Set (Age: 3+)',
        description: 'Build creativity and imagination with this high-quality, 60-piece block set. Made from naturally finished and smooth-sanded hardwood blocks, this set comes in a convenient wooden storage crate (13” L x 12” W x 2” H).',
        buy: '',
    },
    boat: {
        side1: 'Little Bird Toy Co Site Photos/boat1.jpg',
        side2: 'Little Bird Toy Co Site Photos/boat2.jpg',
        side3: 'Little Bird Toy Co Site Photos/boat3.jpg',
        display: 'Little Bird Toy Co Site Photos/boat1.jpg',
        title: 'Handcrafted Wooden Toy Boat (Age: All ages)',
        description: 'Set sail for bathtub adventures with this adorable wooden boat. Made from solid Maine white pine, this handcrafted toy floats and features rounded edges for safety. Includes two peg "lobster people." Size: 10.5"W x 3.5"H.        ',
        buy: '',
    },
    car: {
        side1: 'Little Bird Toy Co Site Photos/car1.jpg',
        side2: 'Little Bird Toy Co Site Photos/car2.jpg',
        side3: 'Little Bird Toy Co Site Photos/car3.jpg',
        display: 'Little Bird Toy Co Site Photos/car1.jpg',
        title: '',
        description: '',
        buy: '',
    },
    train: {
        side1: 'Little Bird Toy Co Site Photos/train1.jpg',
        side2: 'Little Bird Toy Co Site Photos/train2.jpg',
        side3: 'Little Bird Toy Co Site Photos/train7.jpg',
        display: 'Little Bird Toy Co Site Photos/tain1.jpg',
        title: 'Handcrafted Wooden Train Set (Age: 3+)',
        description: 'Embark on a charming journey with this beautiful handcrafted wooden train set. Engine and three interchangeable cars boast intricate details made from real beech wood. Large size (84cm L x 11cm H x 13cm W) with moving wheels and a fully ecological design.        ',
        buy: '',
    },
    plane: {
        side1: 'Little Bird Toy Co Site Photos/plane1.jpg',
        side2: 'Little Bird Toy Co Site Photos/plane2.jpg',
        side3: 'Little Bird Toy Co Site Photos/plane3.jpg',
        display: 'Little Bird Toy Co Site Photos/plain1.jpg',
        title: "'Polished n Sanded' Wooden Airplane (Age: Toddlers)",
        description: 'Soar through imaginative skies with this classic wooden airplane. Handcrafted from sustainable Baltic birch wood with a safe, natural harvest finish and a spinning propeller. Measures 3.5"H x 7"L x 7"W.        ',
        buy: '',
    },
    bar: {
        side1: 'Little Bird Toy Co Site Photos/bar1.jpg',
        side2: 'Little Bird Toy Co Site Photos/bar2.jpg',
        side3: 'Little Bird Toy Co Site Photos/bar3.jpg',
        display: 'Little Bird Toy Co Site Photos/bar1.jpg',
        title: "'Snapz' Play Bars and Connectors (Age: All Ages)",
        description: "Discover endless creative possibilities with Snapz' Play Bars and Connectors, perfect for all ages at Little Bird Toy Shop. These versatile wooden pieces allow children to construct and design a variety of structures, encouraging imaginative play and problem-solving skills. Crafted from high-quality, eco-friendly wood, Snapz' ensures durability and safety for hours of engaging fun. Measures 3.5'H x 7'L x 7'W.",
        buy: '',
    },
}